export const BUILD_LISTING_REQUEST = "BUILD_LISTING_REQUEST";
export const BUILD_LISTING_SUCCESS = "BUILD_LISTING_SUCCESS";
export const BUILD_LISTING_FAILED = "BUILD_LISTING_FAILED";
export const BUILD_LISTING_EMPTY = "BUILD_LISTING_EMPTY";

export const BUILD_LISTING_LAZY_REQUEST = "BUILD_LISTING_LAZY_REQUEST";
export const BUILD_LISTING_LAZY_SUCCESS = "BUILD_LISTING_LAZY_SUCCESS";
export const BUILD_LISTING_LAZY_FAILED = "BUILD_LISTING_LAZY_FAILED";

export const UPDATE_BUILD_BASELINE_REQUEST = "UPDATE_BUILD_BASELINE_REQUEST";
export const UPDATE_BUILD_BASELINE_SUCCESS = "UPDATE_BUILD_BASELINE_SUCCESS";
export const UPDATE_BUILD_BASELINE_FAILED = "UPDATE_BUILD_BASELINE_FAILED";

export const DELETE_BUILD_LISTING_REQUEST = "DELETE_BUILD_LISTING_REQUEST";
export const DELETE_BUILD_LISTING_SUCCESS = "DELETE_BUILD_LISTING_SUCCESS";
export const DELETE_BUILD_LISTING_FAILED = "DELETE_BUILD_LISTING_FAILED";

export const BUILDNAME_EDIT_REQUEST = "BUILDNAME_EDIT_REQUEST";
export const BUILDNAME_EDIT_SUCCESS = "BUILDNAME_EDIT_SUCCESS";
export const BUILDNAME_EDIT_FAILED = "BUILDNAME_EDIT_FAILED";

export const SEARCH_BUILD_KEYWORD_REQUEST = "SEARCH_BUILD_KEYWORD_REQUEST";
export const SEARCH_BUILD_KEYWORD_SUCCESS = "SEARCH_BUILD_KEYWORD_SUCCESS";
export const SEARCH_BUILD_KEYWORD_FAILED = "SEARCH_BUILD_KEYWORD_FAILED";
