export const TEST_COMAPARISON_LIST_REQUEST = "TEST_COMAPARISON_LIST_REQUEST";
export const TEST_COMAPARISON_LIST_SUCCESS = "TEST_COMAPARISON_LIST_SUCCESS";
export const TEST_COMAPARISON_LIST_FAILED = "TEST_COMAPARISON_LIST_FAILED";

export const TEST_COMPARISON_RESULT_REQUEST = "TEST_COMPARISON_RESULT_REQUEST";
export const TEST_COMPARISON_RESULT_SUCCESS = "TEST_COMPARISON_RESULT_SUCCESS";
export const TEST_COMPARISON_RESULT_FAILED = "TEST_COMPARISON_RESULT_FAILED";
export const TEST_COMPARISON_RESULT_EMPTY = "TEST_COMPARISON_RESULT_EMPTY";
