export const TOKEN_FOUND = "TOKEN_FOUND";
export const TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAILED = "USER_DETAILS_FAILED";
