export const PROJECT_LISTINGS_REQUEST = "PROJECT_LISTINGS_REQUEST";
export const PROJECT_LISTINGS_SUCCESS = "PROJECT_LISTINGS_SUCCESS";
export const PROJECT_LISTINGS_FAILED = "PROJECT_LISTINGS_FAILED";

export const PROJECT_FAVORITE_REQUEST = "PROJECT_FAVORITE_REQUEST";
export const PROJECT_FAVORITE_SUCCESS = "PROJECT_FAVORITE_SUCCESS";
export const PROJECT_FAVORITE_FAILED = "PROJECT_FAVORITE_FAILED";

export const PROJECTNAME_EDIT_REQUEST = "PROJECTNAME_EDIT_REQUEST";
export const PROJECTNAME_EDIT_SUCCESS = "PROJECTNAME_EDIT_SUCCESS";
export const PROJECTNAME_EDIT_FAILED = "PROJECTNAME_EDIT_FAILED";

export const PROJECT_FILTER_REQUEST = "PROJECT_FILTER_REQUEST";
export const PROJECT_FILTER_SUCCESS = "PROJECT_FILTER_SUCCESS";
export const PROJECT_FILTER_FAILED = "PROJECT_FILTER_FAILED";
