export const CREATE_NEWPROJECT_TAGS_REQUEST = "CREATE_NEWPROJECT_TAGS_REQUEST";
export const CREATE_NEWPROJECT_TAGS_SUCCESS = "CREATE_NEWPROJECT_TAGS_SUCCESS";
export const CREATE_NEWPROJECT_TAGS_FAILED = "CREATE_NEWPROJECT_TAGS_FAILED";

export const CREATE_NEWPROJECT_APPROVERS_REQUEST =
  "CREATE_NEWPROJECT_APPROVERS_REQUEST";
export const CREATE_NEWPROJECT_APPROVERS_SUCCESS =
  "CREATE_NEWPROJECT_APPROVERS_SUCCESS";
export const CREATE_NEWPROJECT_APPROVERS_FAILED =
  "CREATE_NEWPROJECT_APPROVERS_FAILED";

export const CREATE_NEW_PROJECT_REQUEST = "CREATE_NEW_PROJECT_REQUEST";
export const CREATE_NEW_PROJECT_SUCCESS = "CREATE_NEW_PROJECT_SUCCESS";
export const CREATE_NEW_PROJECT_FAILED = "CREATE_NEW_PROJECT_FAILED";

export const Empty_new_project_State = "Empty_new_project_State";
